"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.metadata = void 0;
const google_1 = require("next/font/google");
require("./globals.css");
const Navbar_1 = __importDefault(require("./component/Navbar"));
const Footer_1 = __importDefault(require("./component/Footer"));
const font = (0, google_1.El_Messiri)({
    subsets: ["latin"],
    weight: ['400']
});
exports.metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};
function RootLayout({ children, }) {
    return (<html lang="en">
      <body className={font.className}>
        <Navbar_1.default />
        {children}
        <Footer_1.default />
        

      </body>
    </html>);
}
exports.default = RootLayout;
