import { El_Messiri } from "next/font/google";
import "./globals.css";
import Navbar from "./component/Navbar";
import Footer from "./component/Footer";



const font = El_Messiri({ 
  subsets: ["latin"],
  weight: ['400']
 });

export const metadata = {
  title: "Create MY PORTFOLIO",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={font.className}>
        <Navbar />
        {children}
        <Footer />
        

      </body>
    </html>
  );
}
